language: node_js
addons:
  chrome: stable
node_js:
  - 5
os:
  - linux
env:
  - NODE_ENV=staging
  - NODE_ENV=production
cache:
  directories:
    - "node_modules"
before_install:
  - gem install bundler
install:
  - npm --production=false install
script:
  - npm run build
after_success:
  - python node_modules/travis-weigh-in/weigh_in.py dist/onfido.min.js
  - chmod ugo+x ./deploy.sh
  - ./deploy.sh
  - chmod ugo+x ./test.sh
  - ./test.sh
